# Generated by Django 5.0 on 2023-12-16 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('std_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_set', to='api.room')),
            ],
        ),
    ]
