# Generated by Django 5.0 on 2024-02-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_teachers',
            name='teacher_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_set', to='api.room'),
        ),
    ]
