# Generated by Django 5.0 on 2024-02-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
